### ISSUE TITLE
Firebase Demo does not load.

### ISSUE THREAD

**Issue by argum** [hansemannn/titanium-firebase-analytics#31] opened 2019-01-21 15:13 UTC
Hello, 

First of all I would thank you for your hard job in order to make the firebase works on titanium :)

I have troubles when I try to build the example app found on your repository. I have just added the **google-services.json**,  **GoogleService-Info.plist** on **Resources** folder and **strings.xml** on **/platform/android/res/values** folder

The tiapp.xml file remains the same as the example app (but I have changed the Titanium SDK to 7.5.0 as is the latest one, but I have also tried 7.0.2, 7.1.1, 7.3.0, 7.4.1.

When I compile the app, the app freezes on splash screen (default titanium splash screen) and the log has the data that you can found on the bottom of my post.

The thing is the Firebase Analytics recognize the device and updates a device and the event "first_time" on the Firebase Analytics Dashboard.

I really need some help to make this works! :)

My setup:
ti.playservices: latest - 11.0.40
Firebase Core: latest 3.0.2
Firebase Analytics : latest 2.2.2
SDK : latest 7.5.0GA (and I have used 7.0.2,7.1.1, 7.3.0, 7.4.1)
Device : Android (Huawei EVA-L09 - Huawei P9 - android 7.0.0)

Thank you!

The console prints the following: 
-- Start application log -----------------------------------------------------
[INFO] :   int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied
[INFO] :   
[INFO] :   Note: log switch off, only log_main and log_events will have logs!
[INFO] :   I/        : power log dlsym ok
[INFO] :   art: Reinit property: dalvik.vm.checkjni= false
[INFO] :   TiApplication: (main) [0,0] checkpoint, app created.
[INFO] :   MultiDex: VM with version 2.1.0 has multidex support
[INFO] :   MultiDex: Installing application
[INFO] :   MultiDex: VM has multidex support, MultiDex support library is disabled.
[INFO] :   FA: App measurement is starting up, version: 11020
[INFO] :   FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
[INFO] :   FA: To enable faster debug mode event logging run:
[INFO] :   FA:   adb shell setprop debug.firebase.analytics.app d2app.idisc.es
[INFO] :   FirebaseInitProvider: FirebaseApp initialization successful
[INFO] :   TiApplication: (main) [132,132] Titanium Javascript runtime: v8
[INFO] :   HwCust: Constructor found for class android.app.HwCustActivityImpl
[INFO] :   HwCust: Constructor found for class android.app.HwCustHwWallpaperManagerImpl
[INFO] :   TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null

**Comment by argum** [comment] 2019-01-21 15:37
[ANDROID] NOTE : I have downgraded the Firebase.Analytics module version to 2.0.0 and it works.

If I check firebaseAnalyitcs.appInstanceID it says "undefined" but log works and Firebase Analytics Dashboard seems to get the data from the device

**Comment by caspahouzer** [comment] 2019-01-22 12:36
same here. 2.0.0 works, but do not set a proper screen name and class on Android. iOS seems to be okay

**Comment by teunklijn** [comment] 2019-01-30 11:21
There seems to be some reference error in version 2.2.2:

```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN8titanium11KrollModule16getProxyTemplateEN2v85LocalINS1_7ContextEEE" referenced by "/data/app/com.sanofi.us.addc-WFL9oxkNesTCLEkCfvH71w==/lib/x86/libfirebase.analytics.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:139)
        at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:113)
        at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:207)
        at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:113)
        at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:135)
        at com.sanofi.us.addc.DupixentApplication.onCreate(DupixentApplication.java:189)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5791)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

**Comment by Jei** [comment] 2019-02-08 11:54
I can confirm that building the module from source solves the problem.

**Comment by hansemannn** [comment] 2019-03-25 21:10
Closing with regards to latest version.

**Closed by hansemannn** 2019-03-25 21:10 UTC
